Docs and raising on qpsi or no single convention being identifiable
Fusion-Power-Plant-Framework/eqdsk pull request #18
Opened 2024-07-04 13:54 UTC by oliverfunk

2024-07-05 07:26 UTC, je-cook requested changes
We should probably detect the eqdsks correctly inc the ones in private data. I think they're either 3, 7 or 11 no 17s

2024-07-05 07:26 UTC, je-cook commented on eqdsk/file.py
> +            anything.
```suggestion
        This sets the internal _cocos attribute and does not return
        anything.
```

2024-07-05 07:26 UTC, je-cook commented on tests/test_file.py
> +            ("DN-DEMO_eqref.json", "json", 7),
this is 3 I think (there is no qpsi), or 7 if you want

2024-07-05 07:26 UTC, je-cook commented on tests/test_file.py
> +            ("DN-DEMO_eqref_withCoilNames.json", "json", 7),
Same here cocos 3

2024-07-05 07:26 UTC, je-cook commented on tests/test_file.py
> +            ({"from_cocos": 17, "to_cocos": 11}, {"from_cocos": 11}),
I dont get how this one can pass as its probably 3

2024-07-05 07:26 UTC, je-cook commented on tests/test_file.py
> +        eqdsk = EQDSKInterface.from_file(file, from_cocos=17, to_cocos=11)
again should be 3

2024-07-10 08:06 UTC, je-cook approved these changes
I like how if you provide 0 data it treats it as unset. We should make sure that is in the docs when we build them!

2024-07-10 08:07 UTC, merged

2024-07-10 08:23 UTC, OceanNuclear approved these changes
Looks good